import { fixupConfigRules } from '@eslint/compat';
import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js';
import { defineConfig } from 'eslint/config';
import prettierConfig from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

const SOURCE_FILES = ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx'];

export default defineConfig([
  {
    ignores: [
      'lib/**',
      'node_modules/**',
      '.yarn/**',
      'example/dist/**',
      // A separate Docusaurus project: web code, its own tsconfig, its own rules.
      'website/**',
      // Regenerated by the Storybook metro plugin on every story change.
      'example/.storybook/storybook.requires.ts',
      'example/android/**',
      'example/ios/**',
    ],
  },
  {
    files: SOURCE_FILES,
    extends: fixupConfigRules(compat.extends('@react-native')),
    rules: {
      'react/react-in-jsx-scope': 'off',
    },
  },
  {
    plugins: { import: importPlugin },
    rules: {
      'no-void': ['error', { allowAsStatement: true }],
      'import/no-named-as-default-member': 'off',
      // `../../../..` chains hide where a module lives; reach for `@/` instead.
      'import/no-relative-parent-imports': 'error',
      'import/order': [
        'error',
        {
          groups: [
            'type',
            ['builtin', 'external'],
            'internal',
            ['parent', 'sibling', 'index'],
          ],
          pathGroups: [
            { pattern: '@/**', group: 'internal' },
            { pattern: '~/**', group: 'internal' },
          ],
          pathGroupsExcludedImportTypes: ['type'],
          'newlines-between': 'never',
        },
      ],
    },
  },
  {
    settings: {
      'import/resolver': {
        node: { extensions: ['.js', '.jsx', '.ts', '.tsx'] },
      },
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'separate-type-imports' },
      ],
      '@typescript-eslint/no-import-type-side-effects': 'error',
      'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
    },
  },
  prettierConfig,
]);
